### PR TITLE
Dockerizing OpenSTA

### PR DESCRIPTION
**Pull request by abdelrahmanhosny**
This pull request proposes packaging OpenSTA in a Docker image. Users don't have to run through lengthy and buggy installation steps. The Docker image is available on Docker Hub (`openroad/opensta`). 

After installing Docker, run OpenSTA using `docker run -it -v $(pwd):/input openroad/opensta` where `-v $(pwd):/input` mounts the current directory to a directory inside the Docker container called `input`, where the input files reside.

### CODE REVIEW

**Comment by jjcherry56** [comment]
you should use cmake instead of autotools, since the autotools is likely to
disappear soon

**Comment by jjcherry56** [comment]
It is also broken because it pulls from your private repo instead of the
github repo.

**Comment by jjcherry56** [comment]
When I build CUDD I don't use any configure args.
I don't bother with 'make check'.
I don't see 'make install' for the results; make a cudd dir someplace and
set path prefix there
and point the sta build to it. Like this:

cd $HOME/cudd-3.0.0
mkdir $HOME/cudd
./configure --prefix $HOME/cudd
make

and then for OpenSTA
build .. -DCUDD=$HOME/cudd

**Comment by jjcherry56** [comment]
try again

cd $HOME/cudd-3.0.0
mkdir $HOME/cudd
./configure --prefix $HOME/cudd
make
make install

and then for OpenSTA
cmake .. -DCUDD=$HOME/cudd
Reply
Forward

**Comment by jjcherry56** [comment]
I pushed an update that has a Dockerfile based on yours that successfully
builds OpenSTA.
I have never used docker before and don't see how to actually run the image.
I think it should use ENTRYPOINT instead of CMD to pass the sta command
file in as
an arg to docker run but it doesn't seem to work properly. It looks like
stdout goes off
to never never land.

**Comment by abdelrahmanhosny** [comment]
Ok. I'm going to rebase my branch on this repo branch and edit the Docker file accordingly. 
`CMD` and `ENTRYPOINT` can be used interchangeably in this context. I will do the testing as well to make sure it works properly. 
Expect an update by late tomorrow.

**Comment by abdelrahmanhosny** [comment]
So, I polished the Dockerfile and updated the README file to point users to how to run the Docker image. I also pushed an image of OpenSTA to Docker Hub at https://cloud.docker.com/u/openroad/repository/docker/openroad/opensta

**Comment by jjcherry56** [comment]
that link 404'd for me

**Comment by abdelrahmanhosny** [comment]
I updated the link. Here it is: https://hub.docker.com/r/openroad/opensta

**Comment by jjcherry56** [comment]
I got it to run as advertised.
One small nit; the run command arg -it should be -i for interactive in
README

**Comment by abdelrahmanhosny** [comment]
According to the official Docker [documentation](https://docs.docker.com/engine/reference/run/#foreground), it says:
```For interactive processes (like a shell), you must use -i -t together in order to allocate a tty for the container process. -i -t is often written -it as you’ll see in later examples.```

I know it works with only `-i` flag, but it doesn't show the `%` sign for the beginning of writing the command. I am not sure what other side effect we might have leaving out the `-t` flag.

**Comment by abdelrahmanhosny** [comment]
Hi James,
Is there any more work to be done on this pull request in order to be merged and closed? :)

**Comment by jjcherry56** [comment]
I don't feel comfortable with the README being so docker centric.
I think that INSTALL may be a better home for it.
The README.md line that has RSPF/DSPF/SPEF should be updated to SPEF to
stay in sync with a recent README edit.

**Comment by abdelrahmanhosny** [comment]
So, can you confirm the following changes to be committed to this merge request?
1. Move the Docker section to the install file. Confirm?
2. I can't see the recent README edit that only has `SPEF` in it. Can you point me out to the line number?

**Pull request merged**
